# Generated by Django 3.0.8 on 2020-07-05 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.CharField(max_length=50)),
                ('Real_name', models.CharField(max_length=50)),
                ('tz', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'AAA',
            },
        ),
        migrations.CreateModel(
            name='Activity_period1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=100)),
                ('end_time', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_period', to='json_api.User1')),
            ],
            options={
                'db_table': 'BBB',
            },
        ),
    ]
